include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names : false
    hash_and_equals : false
    avoid_positional_boolean_parameters : false
    unsafe_html : false
    require_trailing_commas : false
    depend_on_referenced_packages : false
    prefer_null_aware_method_calls : false
    implementation_imports : false

